### PR TITLE
Fixed various dead links

### PR DESCRIPTION
**Pull request by phonk**
The ii, crow studies, update instructions, and technical links are broken, I've pointed them to the correct places.

### CODE REVIEW

**Comment by tehn** [comment]
none of these are actually broken for me (check the live site?)

they might be throwing errors if you're running a local copy of docs?

it's better for us to use relative paths instead of specifying the full URL in the code. let me know what you're seeing on the live monome.org/docs page in terms of errors

**Comment by trentgill** [comment]
Confirmed these links are working fine for me. @phonk what browser / OS are you using? Can you double check the current live site isn't working?

**Comment by phonk** [comment]
They look fine now, I don't know how, but yesterday, on the live site, on my system (Mac, Catalina, Safari) they were broken, everyone of them pointed to a GitHub 404.

**Comment by tehn** [comment]
we'll keep an eye out, closing for now

**Pull request closed without merging**
