### PR TITLE
Improved script-reference

### PR DESCRIPTION
**Pull request by neauoire**
- Added links to each API.
- Added midi/hid docs.
- Added basic examples.

### CODE REVIEW

**Comment by neauoire** [comment]
I do, but it's kind of a circular problem for me at this point, I cannot write docs for it, since there are no .. docs for it. 

The current list of methods taken from the refs, is not really explaining how to use it, I've tried to use this in tutorial code and I never managed to get something that worked reliably so I cannot document it. I'd say, until we have a study that demonstrates how to use it, I'd not include it in the script-reference. Once we have that, I would add it here as well.

**Comment by tehn** [comment]
fair enough! and this rationale prods it higher on my priority list, thanks.

**Comment by neauoire** [comment]
I'm actually really anxious to get started messing with softcut!
✊

**Comment by tehn** [comment]
tomorrow then!

**Pull request merged**
