### PR TITLE
add instructions for new mount path

### PR DESCRIPTION
**Pull request by tyleretters**

### CODE REVIEW

**Review by tehn — COMMENTED** [review]
thanks, this is great! i'm wondering if a half-sentence is necessary to clarify that modifying this file requires ssh'ing into the device.

wondering if this should go in a development guide instead?

or perhaps we should break up the wifi page into a subpage so it's more quickly identifiable which sections are the foundational uses vs. advanced uses

also i see that we don't have a section for sshfs, but we do have a subpage (contributed) for sftp

@dndrks

**Comment by tyleretters** [comment]
sorry for the delay in responding. i added the ssh line and found some errors with the password section.

where is the subpage for sshfs?

**Comment by tehn** [comment]
afaik there isn't one, as i just ran

ag sshfs

from my docs folder and it came up blank

my suggestion is to split some of this into subpages. i believe any sshfs info is buried in the forum.

**Comment by tyleretters** [comment]
see #340

**Pull request closed without merging**
