### PR TITLE
theme upgrade

### PR DESCRIPTION
**Pull request by tyleretters**
**please test the new setup instructions in README.md with a fresh `git clone..`** as this PR is largely to improve developer quality of life! i tested several times and it works but i want to make sure there are no global dependencies / setup instructions that need to be added.

- upgrades to latest just-the-docs (note the release is titled v0.3.3 but the .gemspec - perhaps erroneously - is at v0.3.2)
- update setup instructions
- add default new search options to _config.yml (appears to be helpful - this is the only functional change)

### CODE REVIEW

**Comment by tehn** [comment]
thank you for this!!

pretty sure my ruby/jekyll/whatever setup is busted. i can't resolve this error:

```
~/Downloads/docs$ jekyll build
Traceback (most recent call last):
	21: from /usr/local/bin/jekyll:23:in `<main>'
	20: from /usr/local/bin/jekyll:23:in `load'
	19: from /var/lib/gems/2.7.0/gems/jekyll-4.1.1/exe/jekyll:8:in `<top (required)>'
	18: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	17: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	16: from /var/lib/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll.rb:209:in `<top (required)>'
	15: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	13: from /var/lib/gems/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	11: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	10: from /var/lib/gems/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	 9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 8: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 7: from /var/lib/gems/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
	 6: from /var/lib/gems/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
	 5: from /var/lib/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /var/lib/gems/2.7.0/gems/ffi-1.13.1/lib/ffi.rb:4:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- 2.7/ffi_c (LoadError)
	22: from /usr/local/bin/jekyll:23:in `<main>'
	21: from /usr/local/bin/jekyll:23:in `load'
	20: from /var/lib/gems/2.7.0/gems/jekyll-4.1.1/exe/jekyll:8:in `<top (required)>'
	19: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	18: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	17: from /var/lib/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll.rb:209:in `<top (required)>'
	16: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	15: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	14: from /var/lib/gems/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	13: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	11: from /var/lib/gems/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 8: from /var/lib/gems/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
	 7: from /var/lib/gems/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
	 6: from /var/lib/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
	 5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /var/lib/gems/2.7.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libffi.so.7: cannot open shared object file: No such file or directory - /var/lib/gems/2.7.0/gems/ffi-1.13.1/lib/ffi_c.so (LoadError)
```

the previous setup step allegedly succeeded. i have `libffi-dev`, freshly reinstalled.

if this works for you i'm happy to just merge. if it breaks i can revert.

**Comment by tyleretters** [comment]
what's the output from `gem install ffi` ?

**Comment by tyleretters** [comment]
this is what my output looks like:

```
mbp@mbp /Users/mbp
% cd Desktop/docs
mbp@mbp /Users/mbp/Desktop/docs
% bundle                                                          (theme-upgrade) docs
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.1
Using public_suffix 4.0.6
Using addressable 2.7.0
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.7
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Fetching em-websocket 0.5.2
Installing em-websocket 0.5.2
Using ffi 1.13.1
Using forwardable-extended 2.6.0
Using i18n 1.8.5
Using sassc 2.4.0
Using jekyll-sass-converter 2.1.0
Using rb-fsevent 0.10.4
Using rb-inotify 0.10.1
Fetching listen 3.3.1
Installing listen 3.3.1
Using jekyll-watch 2.2.1
Using rexml 3.2.4
Using kramdown 2.3.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.4.0
Using pathutil 0.16.2
Fetching rouge 3.25.0
Installing rouge 3.25.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using jekyll 4.1.1
Fetching jekyll-redirect-from 0.16.0
Installing jekyll-redirect-from 0.16.0
Fetching jekyll-seo-tag 2.7.1
Installing jekyll-seo-tag 2.7.1
Using just-the-docs 0.3.2 from source at `.`
Bundle complete! 2 Gemfile dependencies, 32 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
mbp@mbp /Users/mbp/Desktop/docs
% jekyll build                                                    (theme-upgrade) docs
Configuration file: /Users/mbp/Desktop/docs/_config.yml
            Source: /Users/mbp/Desktop/docs
       Destination: /Users/mbp/Desktop/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 7.418 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
mbp@mbp /Users/mbp/Desktop/docs
% bundle exec jekyll serve --baseurl '/docs' --watch              (theme-upgrade) docs
Configuration file: /Users/mbp/Desktop/docs/_config.yml
            Source: /Users/mbp/Desktop/docs
       Destination: /Users/mbp/Desktop/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 7.584 seconds.
 Auto-regeneration: enabled for '/Users/mbp/Desktop/docs'
    Server address: http://127.0.0.1:4000/docs/
  Server running... press ctrl-c to stop.
[2020-11-24 19:06:03] ERROR `/docs/favicon.ico' not found.
```

**Comment by tehn** [comment]
i obviously don't know how to use ruby ;)

this is working great now.

**Review by tehn — APPROVED** [review]

**Pull request merged**
