### PR TITLE
less cryptic norns doc structure

### PR DESCRIPTION
**Pull request by dndrks**
folds in changes to the norns docs structure based on Steven's feedback about beginner approachability:

norns
- play
- apps
- manage
     - maiden
     - webDAV
     - SFTP
- scripting
     - studies
     - script reference
     - scripting faq
- help

### CODE REVIEW

**Comment by dndrks** [comment]
@tehn , can you plz take a look and lmk thoughts? <333

**Comment by tehn** [comment]
cool!

lots of redundant words in the scripting area. how about:

- scripting
  - studies
  - reference
  - faq

and "manage" is somewhat upsettingly unromantic :)

trying to come up with other words...  maybe "connect" (really up for suggestions)

**Comment by dndrks** [comment]
for sure re: manage. "connect" makes me think folks might go there for WIFI tips, tho. so maybe we can pull the "connect" section out of play and into its own landing page, which then breaks into maiden / webDAV / SFTP?

**Comment by tehn** [comment]
oh, agreed--- i'm thinking harder about this now

i just didn't want to relegate maiden to be about management given it is much more, a "core" thing of norns.

perhaps better: go back to "manage" and have it be a single page which combines WebDAV and SFTP (and eventually SMB i think). and then maiden gets its own toplevel page?

**Comment by dndrks** [comment]
dope, yeh. i had a nagging feeling about reducing maiden’s visibility. this
is better!

what about “exchange”?

**Comment by tehn** [comment]
i'm actually ok with manage. it's really about file management. and feel ok with it given maiden is top-leveled

**Comment by dndrks** [comment]
@tehn , dope -- added `maiden` back into top level, filled out the `manage` section to include backup to USB / no wifi

**Review by tehn — APPROVED** [review]

**Pull request merged**
