### PR TITLE
Meadowphysics Docs update

### PR DESCRIPTION
**Pull request by cmcavoy**
Updates to the MP module docs based on 2.1 changes. This branch isn't ready to be merged, it doesn't have images and most likely needs some editing / word-smithing. Several parts are cut and pasted from lines threads, so might need some voice consolidation / blending. 

I thought a PR would help reviewers.

### CODE REVIEW

**Comment by tehn** [comment]
i'm in sweden until next week. i can likely get this done by next friday

**Comment by cmcavoy** [comment]
No rush!

**Comment by cmcavoy** [comment]
Quick update, I have the illustrator files necessary to finish this. Will work with my graphic designer wife to finish this up. No ETA, but would like to be done sooner than later.

**Comment by tehn** [comment]
checking in on this! how's it going?

**Comment by cmcavoy** [comment]
Hello!

I'm going to add the illustrator templates to this PR, that's the blocker for me. I think the text is all ready to go (could use another set of eyes to confirm), just need the graphics. I haven't been able to get time from mrs. @cmcavoy to do the updates. From my POV, if the text is ok - just release that and then see if we can get a designer volunteer on lines to finish up the graphics?

**Comment by cmcavoy** [comment]
@tehn looks like the images from the ansible docs are ok to use here. None of the ones I pulled over include the ability to choose notes / cv out, so this is good to go. I cleaned up a bit of the language on a re-read.

I think this is ready to merge.

**Comment by tehn** [comment]
spectacular, thank you.

i'm going to copy v1 to a backup file to link it as some people may have/prefer the old version. will get this merged after i do that.

**Comment by cmcavoy** [comment]
The 1.x code isn't tagged in the MP repo. If that's possible, can't hurt. Definitely a different approach than 2.1.

**Comment by tehn** [comment]
i’ll find the final commit of 1.x

**Comment by tehn** [comment]
i've located the v1 firmware commit, noted it in the newly-saved mp1.md.

can you fix this merge? also we don't need the .zip file included.

**Comment by cmcavoy** [comment]
Made a change to resolve the merge issue that may break links. I moved the 1.x MP docs into a subfolder called MP1 and 2.x into MP2. I changed the permalink tag at the top of each index, but I'm not sure what links to these pages, so it might be an issue. @tehn your last commit deleted the meadowphysics/index.md...not sure if that was your intention. Do you want to have two folders (the way I have it now?) or were you just trying to save the docs generally? Either way works...if you don't like this split into two folders, I can move the MP2 docs back into `/meadowphysics`.

**Comment by tehn** [comment]
i'd keep v2 in /meadowphysics/ and v2 be its own subfolder, thanks.

**Comment by tehn** [comment]
updated comment, sorry. v1 should be a subfolder. current version (v2) stays in root.

**Comment by cmcavoy** [comment]
Got it...i'll make that change in a bit.

**Comment by cmcavoy** [comment]
Ok, updates made.

**Comment by tehn** [comment]
amazing!! thank you!

**Pull request merged**
