### PR TITLE
add system globals

### PR DESCRIPTION
**Pull request by tyleretters**

### CODE REVIEW

**Comment by tehn** [comment]
thanks for jumping on this so quick.

i'd prefer to split this table at least into sections with the norns globals vs. native lua globals... which will help this be more informative rather than just "don't overwrite these"

quick google: https://developer.roblox.com/en-us/api-reference/lua-docs/Lua-Globals

**Comment by tyleretters** [comment]
yeah! good call. i'll take this on as a learning exercise.

**Comment by tyleretters** [comment]
@tehn i split it out based on what was on that page but some of these seem odd. for example  `rawlen`, `rawset`, `require`, `string`... is this link you shared exhaustive?

**Comment by tehn** [comment]
looking good!

remaining system globals in the other col:

- bit32
- dofile
- io
- load
- loadfile
- math (though it's a std lib, we just require it by default)
- os
- rawlen
- rawset
- require
- table
- utf8

**Comment by tyleretters** [comment]
updated!

**Review by tehn — APPROVED** [review]

**Pull request merged**
