### PR TITLE
add nest studies to #contributed knowledge

### PR DESCRIPTION
**Pull request by andr-ew**
this seems helpful to exist here but also maybe not !

### CODE REVIEW

**Review by tehn — COMMENTED** [review]
this is cool, but i think it's miscategorized: you're adding a library to a general documentation space.

@dndrks should we create a section pointing at library documentation? or does this fall more appropriately under norns.community? (ie, make a "libraries" category on the wiki?)

**Comment by andr-ew** [comment]
I came here after considering whether or not it made sense to submit it to norns.community :) up to ya'll !

one thing to note is that the full docs & studies don't at all fit in a norns.community page so it'll be linking out to github either way

**Comment by tehn** [comment]
FYI it's totally fine for norns.community entries to simply link to
external docs--- may do this already (and i plan to do this when i add my
stuff some day)

**Comment by andr-ew** [comment]
on norns.commity now 😎 https://norns.community/en/libs-and-engines

**Pull request closed without merging**
