### PR TITLE
Ansible Earthsea Documentation

### PR DESCRIPTION
**Pull request by infovore**
This PR includes:

* documentation for Ansible Earthsea
* some tweaks to Ansible Kria documentation, I believe

note that `ansible/index.md` falls into the category of 'large updates' and as such you'll need to unfurl it in the PR.

I'm also aware that this PR can't be auto-merged. I don't think any information has been lost - rebasing markdown is painful, to say the least. Let me know what you all think; I think @scanner-darkly is an important reviewer on this.

### CODE REVIEW

**Comment by tehn** [comment]
i'll fix the merge now!

**Comment by infovore** [comment]
eep - I am not sure this actually describes the code that is currently available in master? I mean, it will do shortly, but I was going to wait to confirm the latest Ansible was released? just me thinking about belt/braces is all.

**Comment by scanner-darkly** [comment]
looks good - thanks for doing this!

**Comment by tehn** [comment]
just merged ansible master, if we need to double-check the docs.

**Comment by infovore** [comment]
oh, cool - and now @scanner-darkly has seen it too.

do we need to push a deploy to the monome site in order to update the [ansible page](https://monome.org/docs/modular/ansible/)?

**Comment by tehn** [comment]
yes i'm happy to deploy it now, though we haven't yet published the official release for ansible... people still have to build it.

@scanner-darkly @csboling any outstanding issues prior to making a release? i might need a hand checking the changelog, much has happened!

**Comment by csboling** [comment]
@tehn I still need to PR new Teletype ops (`ANS.#`, `KR.PG`, `KR.CUE`) to Ansible and Teletype (ready to go, will push these tonight) and then I think we're good. I'll update the CHANGELOG.md for Teletype, is there a corresponding place to list changes for Ansible?

**Comment by scanner-darkly** [comment]
@tehn no issues i'm aware of

**Pull request merged**
