### PR TITLE
fenced code styling

### PR DESCRIPTION
**Pull request by pq**
i'm not 100% this is preferred to the existing monochrome (and whether it plays nice with jekyll).

consider it as food for thought?

🤔 

/cc @tehn

### CODE REVIEW

**Comment by tehn** [comment]
@pq did it change? https://monome.org/docs/crow/

**Comment by pq** [comment]
partly!

lua looks good:

image


console is un-styled:

image

**Comment by pq** [comment]
@tehn: do you know if jekyll is using pygments or rouge?

https://jekyllrb.com/docs/liquid/tags/#stylesheets-for-syntax-highlighting

**Comment by pq** [comment]
(or wait, maybe that's not even the right question...  will follow up in dm)

**Pull request merged**
