### PR TITLE
update study4 to 2.0

### PR DESCRIPTION
**Pull request by okyeron**
update study4 to 2.0

### CODE REVIEW

**Comment by tehn** [comment]
thanks! i'm going to hold off on this merge until 2.0 is formally released.

**Comment by simonvanderveldt** [comment]
@tehn @okyeron is this PR still relevant?

**Comment by okyeron** [comment]
Some of it is relavant- although the study has been changed since this PR. However, Study 4 as it is today on the monome site is probably not functional.

there's still a `counter = metro.alloc()`

and `music = require 'mark_eats/musicutil'` is no longer correct.

and reference to `check out the dust repo for the current user libraries.` is outdated.

it probably also needs some details on obtaining the `Passerby` library.

**Comment by okyeron** [comment]
Will submit new pull against the current version

**Pull request closed without merging**
