### PR TITLE
updated Kria pattern docs

### PR DESCRIPTION
**Pull request by mtallen**
Hey guys I have done a first past on updating/expanding the pattern section of the Kria docs. would love to get some feedback. Also is it ok to put the great video by n-So on the documents page? It doesn't really match the aesthetics of the current video set by @tehn but its super easy to follow and is a great example. 

https://www.youtube.com/watch?v=ZWBXLsbxWlw

anyway let me know if there is stuff I should change/ reword, and more importantly where I should post this on lines to get community feedback.

### CODE REVIEW

**Comment by tehn** [comment]
thank you for taking this on!

a link to the video would be good-- but i'd prefer not to have it embedded inline.

**Comment by mtallen** [comment]
Ok ill just add a link then.

**Comment by tehn** [comment]
i need to merge the firmware, then we can announce a new version

**Comment by mtallen** [comment]
Thanks for your support with all this.

**Pull request merged**
